# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      analyzers-packages:
        patterns:
          - "SonarAnalyzer.CSharp"
          - "*.Analyzers"
      test-packages:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "xunit*"
          - "coverlet.collector"
      benchmark-packages:
        patterns:
          - "BenchmarkDotNet*"
      tools:
        patterns:
          - "dotnet-stryker"
          - "dotnet-config"
          - "dotnet-reportgenerator-globaltool"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: nuget
    directory: /benchmarks/OffDotNet.Pdf.Core.Benchmarks
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/OffDotNet.Pdf.CodeAnalysis
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/OffDotNet.Pdf.Console
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/OffDotNet.Pdf.Core
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/OffDotNet.Pdf.Document
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/OffDotNet.Pdf.CodeAnalysis.Old.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/OffDotNet.Pdf.CodeAnalysis.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/OffDotNet.Pdf.Core.Tests
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /tests/OffDotNet.Pdf.Document.Tests
    schedule:
      interval: daily
