version = 1

test_patterns = [
    "tests/**",
]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
enabled = false
name = "csharp"

[[transformers]]
enabled = false
name = "dotnet-format"